snowflake_dw:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: cd43773.sa-east-1.aws

      # User/password auth
      user: AIRBYTE_USER
      password: daniella

      role: AIRBYTE_ROLE
      database: AIRBYTE_DATABASE
      warehouse: AIRBYTE_WAREHOUSE
      schema: AIRBYTE_SCHEMA
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt-q

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)